import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AOSInitializer from "./components/setup/aos-initializer";
import { AlertContainer } from "./components/ui/alert/Alert";
import { AlertProvider } from "./providers/AlertProvider";
import { FontAwesomeSetup } from "./components/setup/font-awesome-setup";

import 'aos/dist/aos.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Votre conseiller personnel en transport - Manage Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/cropped-arbre-de-vie-32x32.png" type="image/png" sizes="32x32" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <FontAwesomeSetup />
        <AlertProvider>
          <AOSInitializer />
          <main className="min-h-screen bg-white">{children}</main>
          <AlertContainer />
        </AlertProvider>
      </body>
    </html>
  );
}
