import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import AOSInitializer from "./components/AOSInitializer";
import { AlertContainer } from "./components/Alert/Alert";
import { AlertProvider } from "./providers/AlertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Votre conseiller personnel en transport - Manage Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/cropped-arbre-de-vie-32x32.png" type="image/png" sizes="32x32" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          <AOSInitializer />
          <Header />
          <main className="min-h-screen bg-white">{children}</main>
          <Footer />
          <AlertContainer />
        </AlertProvider>
      </body>
    </html>
  );
}
